### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaFEM/BoundingSphere.jl#19]
Do we need a new release? Or should we wait for the documentation pull request #12 to be merged? 

We are dropping julia 0.6 and 0.7 support. Therefore we will need a minor revision. Or should we release v1.0.0?

**Comment by jw3126** [comment]
I think a `v0.2.0` release cannot hurt.

**Comment by TeroFrondelius** [comment]
@jw3126 v0.2.0 now or after fixing the documentation? I want to do it now.

**Comment by TeroFrondelius** [comment]
@JuliaRegistrator register()

**Comment by TeroFrondelius** [comment]
I decided we can release v0.2.1 when the documentation is fixed.

**Comment by TeroFrondelius** [comment]
Done
