### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by jw3126** [JuliaFEM/BoundingSphere.jl#5]
It would be cool to release this package soon. Here is the minimum that needs to be done before the first release:

- [x] Fix codecov
- [x] Add JuliaFEM to license
- [ ] u̶s̶e̶ ̶P̶k̶g̶T̶e̶s̶t̶S̶u̶i̶t̶e̶.̶j̶l̶

In addition there are the JuliaFEM coding standards that we probably want here like license headers etc. that I am not so familiar with.

**Comment by TeroFrondelius** [comment]
Yes definately I agree. Both I and Jukka are on the vacation at the moment thus the slow response times. I could take the licence stuff but nothing will happen in next eleven days.

**Comment by jw3126** [comment]
Okay thanks, happy vacation!

**Comment by ahojukka5** [comment]
Other JuliaFEM packages uses PkgTestSuite to run CI somewhat standard way (see e.g. FEMBase.jl .travis.yml), I suggest we use that as it checks that license headers are correct, tabulators are not used in code and also some other things in future. License header in this package is then

```
# This file is a part of JuliaFEM.
# License is MIT: see https://github.com/JuliaFEM/BoundingSphere.jl/blob/master/LICENSE
```

**Comment by jw3126** [comment]
@ahojukka5 sure! Can you set this up?

**Comment by jw3126** [comment]
I would like to release this package as is and announce it on discourse.
Anything missing @TeroFrondelius  @ahojukka5 @ovainola?

Here is a draft of what I would like to post, are you okay with it?

# ANN: BoundingSphere.jl 

[BoundingSphere.jl](https://github.com/JuliaFEM/BoundingSphere.jl) is a package, that allows to find smallest spheres that enclose a given set of points. Basic usage is as follows:

```julia
using BoundingSphere

pts = [randn(3) for _ in 1:10]
center, radius = boundingsphere(pts)

using StaticArrays
pts = [@SVector(randn(3)) for _ in 1:10] # use static arrays for performance
algorithm = Ritter() # fast but inaccurate
center, radius = boundingsphere(pts, algorithm) # customize algorithm
```
[BoundingSphere.jl](https://github.com/JuliaFEM/BoundingSphere.jl) is the successor of [Miniball.jl](https://github.com/JuliaFEM/Miniball.jl) and maintained by Jukka Aho, Tero Frondelius, @ovainola and myself.

**Comment by TeroFrondelius** [comment]
Looks good to me. My understanding of semantic version numbering is that first version is 0.1.0. So if you haven't yet tagged, I propose to tag 0.1.0.

**Comment by jw3126** [comment]
Yes 0.1.0 sounds good. I will tag and announce at the beginning of next week, if no issue come up.

**Comment by jw3126** [comment]
https://discourse.julialang.org/t/ann-boundingsphere-jl/14127
